-- MySQL Script generated by MySQL Workbench
-- Wed Jun 22 14:50:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sae24
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sae24
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sae24` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sae24` ;

-- -----------------------------------------------------
-- Table `sae24`.`capteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae24`.`capteur` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `piece` VARCHAR(45) NOT NULL,
  `emplacement` VARCHAR(45) NULL DEFAULT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`numero`),
  UNIQUE INDEX `idCapteur_UNIQUE` (`numero` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sae24`.`donnee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae24`.`donnee` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `timestomp` TIMESTAMP(6) NOT NULL,
  `temperature` INT NOT NULL,
  PRIMARY KEY (`numero`),
  UNIQUE INDEX `iddonnee_UNIQUE` (`numero` ASC) VISIBLE,
  UNIQUE INDEX `timestomp_UNIQUE` (`timestomp` ASC) VISIBLE,
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `sae24`.`capteur` (`numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
